### ISSUE TITLE
how to use the persistence in "activemq"

### ISSUE THREAD

**Issue by chuangyou** [go-mqtt/mqtt#3]
how to use the persistence in "activemq"

**Comment by cmars** [comment]
This is a github fork of an upstream, which was made primarily to work around a code.google.com dependency.

I would recommend asking [here](https://github.com/go-mqtt/mqtt#reporting-bugs) per the README. For better response there, I'd recommend being more specific with the question, such as, "Do you have any examples of how to using MQTT-Go with ActiveMQ?"

I don't use MQTT-Go with ActiveMQ, so I'm sorry, I can't help you there.
