### ISSUE TITLE
Release/Transfer go-mqtt org

### ISSUE THREAD

**Issue by magiconair** [go-mqtt/mqtt#4]
Dear go-mqtt team,

I am an open-source maintainer of three active projects and author of a third one. My current employer https://github.com/northvolt has sponsored some of them.

* https://github.com/magiconair/properties
* https://github.com/gopcua/opcua (sponsored by Northvolt)
* https://github.com/gotwincat/twincat (also sponsored by Northvolt)
* https://github.com/fabiolb/fabio (original author)

We would like to open-source another project which is a new MQTT driver for Go. The driver has already been written (http://github.com/pascaldekloe/mqtt) and should be moved to a neutral organization to relieve the author and invite a larger community.

The https://github.com/gomqtt organization would be the best fit but that name is taken. However, there are no people and no repositories so it looks like it is squatted and Github won't release it.

https://github.com/go-mqtt is the next best fit but it contains code which at least might be in use even though it has not been maintained over the last 6 years.

I am wondering whether you would be OK to transfer the go-mqtt organization so that we can host the new driver?

Thank you and with best regards
Frank Schröder

**Comment by cmars** [comment]
I'm generally +1 on this, but will need to confer with colleagues who collaborated on this. Been super busy this week, but will get back to you soon!

**Comment by magiconair** [comment]
Thank you for the quick response.

**Comment by cmars** [comment]
Other thing I'm wondering is, is anyone currently importing this code? Will need to check pkg.go.dev for example. I don't think it'd be right to pull the rug out from under a downstream importer (if there are any).

**Comment by magiconair** [comment]
What did you change? Mainline has moved on a bit

**Comment by magiconair** [comment]
We can also notify the importers if there are any.

**Comment by magiconair** [comment]
Thank you. I will talk to the author of the driver so that we can transfer the repo. I will rename the old repo and archive it and remove it after a month unless you think it is OK to remove it right away. 

I'll also make sure to mention that you and your team provided the org and add a nice link to https://wiregarden.io. Do you have a logo that I can use?

BTW, this looks like a cool project and we might actually need something like this for our own setup. I'll have a closer look.

**Comment by cmars** [comment]
@magiconair You're most welcome! I've added you to the org as an owner. Github's permissions/controls are a little strange... seems like you can transfer projects, but I didn't see anything about transferring orgs. I _think_ this should give you what you need, if not, please let me know how I can be of further assistance!

Sorry again for the delay. First week at a new company was pretty busy!

Northvolt looks like a really cool company doing awesome work. Thanks for taking this over, and I wish you all the best!

**Comment by magiconair** [comment]
I think you've reacted exceptionally quick :)
